package com.eduardobm.jbossadmin;

import java.awt.Color;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author casto
 */
public class MainJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJDialog.class.getName());
    private static final Color VALID_JBOSS_PATH_COLOR = new Color(0, 153, 0);
    private static final Color INVALID_JBOSS_PATH_COLOR = Color.RED;

    /**
     * Creates new form MainJDialog
     */
    public MainJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configureJbossPathValidation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBossPathJTextField = new javax.swing.JTextField();
        runStopJToggleButton = new javax.swing.JToggleButton();
        debugJCheckBox = new javax.swing.JCheckBox();
        addArtifactJButton = new javax.swing.JButton();
        artifactJTextField1 = new javax.swing.JTextField();
        removeJButton1 = new javax.swing.JButton();
        clearAllJButton = new javax.swing.JButton();
        deployJButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("JBoss Admin Tools for IntelliJ Community");

        jLabel2.setText("JBoss path:");

        jBossPathJTextField.setText("C:/...");
        jBossPathJTextField.addActionListener(this::jBossPathJTextFieldActionPerformed);

        runStopJToggleButton.setText("stop");

        debugJCheckBox.setText("debug");

        addArtifactJButton.setText("add a project artifact path");
        addArtifactJButton.addActionListener(this::addArtifactJButtonActionPerformed);

        artifactJTextField1.setText("C:/..");
        artifactJTextField1.addActionListener(this::artifactJTextField1ActionPerformed);

        removeJButton1.setText("remove");

        clearAllJButton.setText("clear all");

        deployJButton1.setText("deploy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addArtifactJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearAllJButton))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBossPathJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(debugJCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(artifactJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deployJButton1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeJButton1)
                            .addComponent(runStopJToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBossPathJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runStopJToggleButton)
                    .addComponent(debugJCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addArtifactJButton)
                    .addComponent(clearAllJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artifactJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeJButton1)
                    .addComponent(deployJButton1))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configureJbossPathValidation() {
        jBossPathJTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validateJbossPath();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateJbossPath();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateJbossPath();
            }
        });
        validateJbossPath();
    }

    public static boolean isValidJbossPath(String jbossPath) {
        if (jbossPath == null || jbossPath.isBlank()) {
            return false;
        }

        Path basePath = Paths.get(jbossPath.trim());
        if (!Files.exists(basePath) || !Files.isDirectory(basePath)) {
            return false;
        }

        Path binPath = basePath.resolve("bin");
        Path modulesPath = basePath.resolve("modules");

        return Files.isDirectory(binPath) && Files.isDirectory(modulesPath);
    }

    private void validateJbossPath() {
        String jbossPath = jBossPathJTextField.getText();
        boolean valid = isValidJbossPath(jbossPath);

        jBossPathJTextField.setForeground(valid ? VALID_JBOSS_PATH_COLOR : INVALID_JBOSS_PATH_COLOR);
        jBossPathJTextField.setToolTipText(valid
                ? "Valid JBoss EAP path"
                : "Invalid JBoss EAP path. Use the root directory containing bin and modules.");
    }

    private void jBossPathJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBossPathJTextFieldActionPerformed
        validateJbossPath();
    }//GEN-LAST:event_jBossPathJTextFieldActionPerformed

    private void addArtifactJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArtifactJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addArtifactJButtonActionPerformed

    private void artifactJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artifactJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artifactJTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainJDialog dialog = new MainJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addArtifactJButton;
    private javax.swing.JTextField artifactJTextField1;
    private javax.swing.JButton clearAllJButton;
    private javax.swing.JCheckBox debugJCheckBox;
    private javax.swing.JButton deployJButton1;
    private javax.swing.JTextField jBossPathJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton removeJButton1;
    private javax.swing.JToggleButton runStopJToggleButton;
    // End of variables declaration//GEN-END:variables
}
