package com.eduardobm.jbossadmin;

import java.awt.Color;
import java.awt.FlowLayout;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author casto
 */
public class MainJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJDialog.class.getName());
    private static final Color VALID_JBOSS_PATH_COLOR = new Color(0, 153, 0);
    private static final Color INVALID_JBOSS_PATH_COLOR = Color.RED;
    private static final Color VALID_ARTIFACT_PATH_COLOR = new Color(0, 153, 0);
    private static final Color INVALID_ARTIFACT_PATH_COLOR = Color.RED;
    private static final Set<String> ACCEPTED_ARTIFACT_EXTENSIONS = Set.of("war", "ear", "jar");

    /**
     * Creates new form MainJDialog
     */
    public MainJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configureJbossPathValidation();
        configureArtifactField(artifactJTextField1, deployJButton1, removeJButton1, true);
        removeJButton1.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBossPathJTextField = new javax.swing.JTextField();
        runStopJToggleButton = new javax.swing.JToggleButton();
        debugJCheckBox = new javax.swing.JCheckBox();
        addArtifactJButton = new javax.swing.JButton();
        artifactJTextField1 = new javax.swing.JTextField();
        removeJButton1 = new javax.swing.JButton();
        clearAllJButton = new javax.swing.JButton();
        deployJButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("JBoss Admin Tools for IntelliJ Community");

        jLabel2.setText("JBoss path:");

        jBossPathJTextField.setText("C:/...");
        jBossPathJTextField.addActionListener(this::jBossPathJTextFieldActionPerformed);

        artifactRowsJPanel = new javax.swing.JPanel();
        artifactRowsJPanel.setLayout(new BoxLayout(artifactRowsJPanel, BoxLayout.Y_AXIS));
        artifactRowsJPanel.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        runStopJToggleButton.setText("stop");

        debugJCheckBox.setText("debug");

        addArtifactJButton.setText("add a project artifact path");
        addArtifactJButton.addActionListener(this::addArtifactJButtonActionPerformed);

        artifactJTextField1.setText("C:/..");
        artifactJTextField1.addActionListener(this::artifactJTextField1ActionPerformed);

        removeJButton1.setText("remove");

        clearAllJButton.setText("clear all");

        deployJButton1.setText("deploy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBossPathJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(debugJCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(runStopJToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addArtifactJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearAllJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(artifactJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deployJButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeJButton1))
                    .addComponent(artifactRowsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBossPathJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debugJCheckBox)
                    .addComponent(runStopJToggleButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addArtifactJButton)
                    .addComponent(clearAllJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artifactJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deployJButton1)
                    .addComponent(removeJButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artifactRowsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configureJbossPathValidation() {
        jBossPathJTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validateJbossPath();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateJbossPath();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateJbossPath();
            }
        });
        validateJbossPath();
    }

    public static boolean isValidJbossPath(String jbossPath) {
        if (jbossPath == null || jbossPath.isBlank()) {
            return false;
        }

        Path basePath = Paths.get(jbossPath.trim());
        if (!Files.exists(basePath) || !Files.isDirectory(basePath)) {
            return false;
        }

        Path binPath = basePath.resolve("bin");
        Path modulesPath = basePath.resolve("modules");

        return Files.isDirectory(binPath) && Files.isDirectory(modulesPath);
    }

    private void validateJbossPath() {
        String jbossPath = jBossPathJTextField.getText();
        boolean valid = isValidJbossPath(jbossPath);

        jBossPathJTextField.setForeground(valid ? VALID_JBOSS_PATH_COLOR : INVALID_JBOSS_PATH_COLOR);
        jBossPathJTextField.setToolTipText(valid
                ? "Valid JBoss EAP path"
                : "Invalid JBoss EAP path. Use the root directory containing bin and modules.");
    }

    public static boolean isValidArtifactPath(String artifactPath) {
        if (artifactPath == null || artifactPath.isBlank()) {
            return false;
        }

        Path artifactFile = Paths.get(artifactPath.trim());
        if (!Files.isRegularFile(artifactFile)) {
            return false;
        }

        String extension = java.nio.file.Path.of(artifactFile.toString()).getFileName().toString();
        int lastDot = extension.lastIndexOf('.');
        if (lastDot < 0 || lastDot == extension.length() - 1) {
            return false;
        }

        String normalizedExtension = extension.substring(lastDot + 1).toLowerCase();
        return ACCEPTED_ARTIFACT_EXTENSIONS.contains(normalizedExtension);
    }

    public static Path deployArtifactToDeployments(String jBossPath, String artifactPath) throws IOException {
        if (!isValidJbossPath(jBossPath)) {
            throw new IllegalArgumentException("Invalid JBoss path");
        }
        if (!isValidArtifactPath(artifactPath)) {
            throw new IllegalArgumentException("Invalid artifact file");
        }

        Path source = Paths.get(artifactPath.trim());
        Path deploymentDirectory = Paths.get(jBossPath.trim(), "standalone", "deployments");
        Files.createDirectories(deploymentDirectory);

        Path target = deploymentDirectory.resolve(source.getFileName().toString());
        Files.move(source, target, StandardCopyOption.REPLACE_EXISTING);
        return target;
    }

    private void configureArtifactField(JTextField artifactField, JButton deployButton, JButton removeButton, boolean removable) {
        artifactField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validateArtifactField(artifactField);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateArtifactField(artifactField);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateArtifactField(artifactField);
            }
        });

        deployButton.addActionListener(evt -> deployArtifact(artifactField));
        removeButton.setEnabled(true);
        if (removable) {
            removeButton.addActionListener(evt -> removeArtifactRow((JPanel) removeButton.getParent()));
        }
        validateArtifactField(artifactField);
    }

    private void validateArtifactField(JTextField artifactField) {
        boolean valid = isValidArtifactPath(artifactField.getText());
        artifactField.setForeground(valid ? VALID_ARTIFACT_PATH_COLOR : INVALID_ARTIFACT_PATH_COLOR);
        artifactField.setToolTipText(valid
                ? "Valid artifact file"
                : "Invalid artifact file. Accepted extensions: .war, .ear and .jar");
    }

    private void deployArtifact(JTextField artifactField) {
        String artifactPath = artifactField.getText();
        if (!isValidArtifactPath(artifactPath)) {
            validateArtifactField(artifactField);
            return;
        }

        if (!isValidJbossPath(jBossPathJTextField.getText())) {
            validateJbossPath();
            return;
        }

        try {
            Path deployedArtifact = deployArtifactToDeployments(jBossPathJTextField.getText(), artifactPath);
            artifactField.setText(deployedArtifact.toString());
            validateArtifactField(artifactField);
        } catch (IOException ex) {
            artifactField.setForeground(INVALID_ARTIFACT_PATH_COLOR);
            artifactField.setToolTipText("Unable to deploy artifact to the JBoss deployments folder.");
            logger.log(java.util.logging.Level.SEVERE, "Unable to deploy artifact", ex);
        }
    }

    private void removeArtifactRow(JPanel artifactRow) {
        if (artifactRow == null) {
            return;
        }
        artifactRowsJPanel.remove(artifactRow);
        artifactRowsJPanel.revalidate();
        artifactRowsJPanel.repaint();
    }

    private void addArtifactRow() {
        JPanel artifactRow = new JPanel();
        artifactRow.setLayout(new BoxLayout(artifactRow, BoxLayout.X_AXIS));
        artifactRow.setBorder(BorderFactory.createEmptyBorder(3, 0, 0, 0));
        artifactRow.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        JTextField newArtifactJTextField = new JTextField("C:/..", 45);
        JButton newDeployJButton = new JButton("deploy");
        JButton newRemoveJButton = new JButton("remove");

        configureArtifactField(newArtifactJTextField, newDeployJButton, newRemoveJButton, true);
        artifactRow.add(newArtifactJTextField);
        artifactRow.add(javax.swing.Box.createHorizontalStrut(5));
        artifactRow.add(newDeployJButton);
        artifactRow.add(javax.swing.Box.createHorizontalStrut(5));
        artifactRow.add(newRemoveJButton);

        artifactRowsJPanel.add(artifactRow);
        artifactRowsJPanel.revalidate();
        artifactRowsJPanel.repaint();
    }

    private void jBossPathJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBossPathJTextFieldActionPerformed
        validateJbossPath();
    }//GEN-LAST:event_jBossPathJTextFieldActionPerformed

    private void addArtifactJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArtifactJButtonActionPerformed
        addArtifactRow();
    }//GEN-LAST:event_addArtifactJButtonActionPerformed

    private void artifactJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artifactJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artifactJTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainJDialog dialog = new MainJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addArtifactJButton;
    private javax.swing.JTextField artifactJTextField1;
    private javax.swing.JPanel artifactRowsJPanel;
    private javax.swing.JButton clearAllJButton;
    private javax.swing.JCheckBox debugJCheckBox;
    private javax.swing.JButton deployJButton1;
    private javax.swing.JTextField jBossPathJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton removeJButton1;
    private javax.swing.JToggleButton runStopJToggleButton;
    // End of variables declaration//GEN-END:variables
}
